<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<_ContentIncludedByDefault Remove="wwwroot\Images\Barber-background.png" />
		<_ContentIncludedByDefault Remove="wwwroot\Images\Hims-Logo.png" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.10">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.6" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Hims.Arquitecture\Hims.Arquitecture.csproj" />
		<ProjectReference Include="..\Hims.Data\Hims.Data.csproj" />
	</ItemGroup>

</Project>




